In [1]:
'''
This script merges all biological knowledge sources and 
exporting into "./data/processed" folder with pbk_layer.txt name.
'''

import os, sys
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath('__file__')))
os.chdir(ROOT_DIR)
sys.path.append(ROOT_DIR)
# importing scripts in scripts folder
from scripts import settings as ssrp, dataset_scripts as dsrp, path_scripts as psrp, model_scripts as msrp
# importing default libraries
import numpy as np
import pandas as pd

# loc_output = os.path.join(ssrp.DIR_DATA_PROCESSED, 'pbk_layer.txt')
loc_output = os.path.join(ssrp.DIR_DATA_PROCESSED)

scripts/settings.py - PATHS IMPORTED!!!

In [2]:
# HSA - HIPATHIA INFORMATION
df_hsa_hipathia = pd.read_csv(os.path.join(ssrp.DIR_DATA_PROCESSED, 'hsa/hipathia/bio_layer_hsa.txt'))
print(df_hsa_hipathia.shape)
df_hsa_hipathia.head()

(2987, 94)

,symbol,hsa03320,hsa04010,hsa04012,hsa04014,hsa04015,hsa04020,hsa04022,hsa04024,hsa04062,...,hsa04925,hsa04960,hsa04961,hsa04962,hsa04970,hsa04971,hsa04972,hsa04973,hsa04976,hsa05100
0,akt3,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,tank,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,foxo6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,kir2ds2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,cldn24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df_hsa_hipathia.to_csv(os.path.join(loc_output, 'pbk_layer_hsa.txt'), index=False)
print('Biological knowledge saved into ->', os.path.join(loc_output, 'pbk_layer_hsa.txt'))

Biological knowledge saved into -> ./data/processed/pbk_layer_hsa.txt

In [5]:
# MMU - HIPATHIA INFORMATION
df_mmu_hipathia = pd.read_csv(os.path.join(ssrp.DIR_DATA_PROCESSED, 'mmu/hipathia/bio_layer_mmu.txt'))
print(df_mmu_hipathia.shape)
df_mmu_hipathia.head()

(3737, 93)

,symbol,mmu03320,mmu04010,mmu04012,mmu04014,mmu04015,mmu04020,mmu04022,mmu04024,mmu04062,...,mmu04925,mmu04960,mmu04961,mmu04962,mmu04970,mmu04971,mmu04972,mmu04973,mmu04976,mmu05100
0,olfr55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,olfr239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,isg15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,gm14548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,sirpb1c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df_mmu_hipathia.to_csv(os.path.join(loc_output, 'pbk_layer_mmu.txt'), index=False)
print('Biological knowledge saved into ->', os.path.join(loc_output, 'pbk_layer_mmu.txt'))

Biological knowledge saved into -> ./data/processed/pbk_layer_mmu.txt