In [4]:
import pandas as pd
import numpy as np

In [2]:
df_retrieval = pd.read_pickle('../data/processed/exper_mouse/mouse_retrieval_sw_StandardScaler.pck')
df_retrieval

,lamc1,il6st,ngef,ghrl,egln3,egln2,egln1,rictor,pycard,arpc4,...,dusp4,dusp7,dusp6,dusp1,tbkbp1,dusp2,junb,jund,avpr1b,cell_type
0,-0.459040,-0.444413,-0.261784,-0.23949,-0.268659,-0.501350,0.598952,-0.347275,-0.403443,-0.244967,...,-0.318303,-0.340731,-0.387759,-0.270464,-0.288853,-0.224094,-0.298094,-0.464241,-0.426253,16cell_
1,-0.363705,-0.444413,-0.261784,-0.23949,-0.268659,-0.169044,1.839704,-0.329705,-0.479394,0.013038,...,-0.318303,-0.205479,-0.387759,-0.315043,-0.288853,-0.224094,-0.298094,-0.339878,-0.426253,16cell_
2,-0.454481,-0.444413,-0.261784,-0.23949,-0.268659,-0.060617,1.397703,-0.544284,-0.479394,-0.678418,...,-0.318303,-0.285115,-0.387759,-0.056582,-0.288853,-0.224094,-0.298094,-0.319694,-0.426253,16cell_
3,-0.459194,-0.444413,-0.261784,-0.23949,-0.268659,0.174457,2.275587,-0.543023,-0.478385,0.267379,...,-0.318303,-0.361859,-0.387043,-0.316655,-0.288853,-0.224094,-0.298094,-0.423918,-0.426253,16cell_
4,-0.438770,-0.444413,-0.261784,-0.23949,0.292098,-0.160120,1.573690,-0.513803,-0.479394,-0.104771,...,-0.318303,-0.330187,-0.387759,-0.301698,-0.240300,-0.224094,-0.298094,-0.400347,-0.426253,16cell_
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17288,-0.459581,-0.440503,-0.261784,-0.23949,-0.268659,-0.501931,-0.392794,-0.108579,-0.103485,-0.159357,...,-0.318303,-0.370142,0.511968,2.063510,-0.288853,-0.172235,0.113664,-0.452236,-0.426253,HSC_old
17289,-0.459581,-0.444413,-0.261784,-0.23949,-0.268659,-0.473480,-0.392794,-0.470384,3.246238,-0.691507,...,-0.318303,-0.370142,-0.373886,1.525462,-0.288853,-0.224094,-0.287803,-0.415331,-0.426253,HSC_old
17290,-0.459581,14.148266,-0.261784,-0.23949,-0.268659,-0.416793,-0.392794,-0.544284,0.504503,-0.257605,...,-0.318303,-0.370142,0.025068,1.273003,-0.288853,-0.224094,-0.140685,-0.337795,-0.426253,HSC_old
17291,-0.459581,6.527850,-0.260317,-0.23949,-0.241763,-0.335165,-0.392794,-0.544284,0.862725,-0.614156,...,-0.318303,-0.002227,1.542133,0.384380,-0.176746,-0.224094,-0.294073,-0.344806,-0.422925,HSC_old
17292,-0.261837,-0.444413,-0.261784,-0.23949,-0.268659,-0.501931,-0.392794,-0.541178,-0.472055,-0.420938,...,-0.318303,-0.370142,0.715790,-0.309411,-0.288853,-0.220213,-0.067148,-0.345897,-0.426253,HSC_old

In [5]:
df_retrieval['cell_type_detail'] = df_retrieval['cell_type']
df_retrieval['cell_type'] = df_retrieval['cell_type'].str.split('_', expand=True)[0]

df_retrieval.loc[df_retrieval.index.isin(np.where(df_retrieval['cell_type'].isin(['E12', 'E14', 'adult']))[0]), 'cell_type'] = 'HSC'
df_retrieval.loc[df_retrieval.index.isin(np.where(df_retrieval['cell_type'].isin(['celebral-cortex', 'CNS', 'brain']))[0]), 'cell_type'] = 'neuron'

In [8]:
df_retrieval = df_retrieval.loc[df_retrieval['cell_type'].isin(['HSC','4cell','ICM','spleen','8cell','neuron','zygote','2cell','ESC'])].reset_index(drop=True)
df_retrieval = df_retrieval.iloc[:, :-1]
# df_retrieval = df_retrieval.loc[df_retrieval['cell_type'].isin(['HSC','4cell','ICM'])].reset_index(drop=True)
print(df_retrieval.shape)

(13645, 1646)

In [11]:
df_retrieval.to_pickle('../data/processed/exper_mouse/mouse_retrieval_cv_sw_StandardScaler.pck')

In [10]:
df_retrieval['cell_type'].value_counts()

ESC       9123
neuron    3667
spleen     420
HSC        202
2cell       85
4cell       55
8cell       53
ICM         22
zygote      18
Name: cell_type, dtype: int64